name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - uses: lowlighter/metrics@latest
        with:
          base: header, activity, repositories
          
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }} 
          config_display: large
          commits_authoring: temirovazat
          config_padding: 0, 8 + 2%
          config_timezone: Asia/Bishkek
          plugin_followup: yes
          plugin_followup_sections: repositories, user
          plugin_people: yes
          plugin_people_types: followers, thanks     
          plugin_people_limit: 28                   
          plugin_people_size: 28                     
          plugin_people_identicons: no               
          plugin_people_sponsors_custom: octocat     
          plugin_people_shuffle: yes  
