name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - uses: lowlighter/metrics@latest
        with:
          base: header, activity, repositories
          
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }} 
          config_display: large
          config_padding: 0, 8 + 2%
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_followup: yes
          plugin_followup_sections: user 
          plugin_lines: yes
          config_timezone: Asia/Bishkek # Set timezone
