name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - uses: lowlighter/metrics@latest
        with:
          base: header, activity, repositories
          
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }} 
          config_display: large
          commits_authoring: temirovazat
          config_padding: 0, 8 + 2%
          config_timezone: Asia/Bishkek # Set timezone
          plugin_languages: yes
          plugin_languages_categories: markup, programming, data, prose
          plugin_languages_details: bytes-size, percentage
          plugin_languages_colors: github
          plugin_languages_limit: 20
          plugin_languages_recent_categories: programming
          plugin_languages_recent_days: 30
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used, recently-used
          plugin_languages_threshold: 0%
